sudo: required

language: python

services:
  - docker

before_install:
  - docker build . -f ./docker/Dockerfile -t milesg/gap-statistic:1.0

script:
  - docker run --rm -v `pwd`:`pwd` -w `pwd` milesg/gap-statistic:1.0 coverage run setup.py test

after_success:
  coveralls