version: 0.2.{build}
environment:
  TARGET: x86_64-pc-windows-msvc
  matrix:
    - PYTHON: "C:/Python35-x64"
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64

    - PYTHON: "C:/Python36-x64"
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

install:
  - call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - conda config --add channels conda-forge --force
  - conda install --yes --quiet cmake flang jom lapack
  #- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.msi"
  - start /wait msiexec /i rust-nightly-%TARGET%.msi INSTALLDIR="%CD%\rust-nightly-%TARGET%" /quiet /qn /norestart
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - set "LIB=%CONDA_INSTALL_LOCN%\Library\lib;%LIB%"
  - set "CPATH=%CONDA_INSTALL_LOCN%\Library\include;%CPATH%"
  - set PATH=%PATH%;%CD%/rust-nightly-%TARGET%/bin
  - rustc -V
  - cargo -V
  - set RUST_BACKTRACE=1

build_script:
  - pip install -r requirements.txt
  - pip install setuptools-rust pytest pytest-benchmark
  - python setup.py build_ext

test_script:
  - cargo test
  - python setup.py install && pytest -v tests