[package]
name = "gap-statistic"
version = "1.1.0"
authors = ["Miles Granger <miles59923@gmail.com>"]

[lib]
name = "gapstatistic"
crate-type = ["cdylib"]

[dependencies]
num = "0.1"
ndarray = "0.11.1"
pyo3 = {version="0.2", features=["extension-module"]}