{% set data = load_setup_py_data() %}

package:
  name: gap-stat
  version: {{ data['version'] }}

source:
  path: ../

build:
  number: 1
  script:
    - pip install gap-stat --no-index --no-deps -f wheelhouse


requirements:
  build:
    - python {{ python }}
    - setuptools
    - pip
  run:
    - python {{ python }}
    - scipy
    - numpy
    - pandas

test:
  imports:
    - gap_statistic
    - gap_statistic.rust.gapstat


about:
  home: http://github.com/milesgranger/gap_statistic
  license: Apache Software License
  summary: Gap Statistic implementation in Python with backend computation written in Rust