
package:
  name: gap_statistic
  version: 1.5.0a

source:
  fn: gap-stat-1.5.0a2.tar.gz
  url: https://files.pythonhosted.org/packages/40/1a/2f8ee08ab6e95bebc95c1363a25ae50ed9b485cbaa16c86a6bc36128d721/gap-stat-1.5.0a2.tar.gz
  sha256: 2a288145de3ebadc81b38ca5e070c69fd5e82c1603d071d3aa0bcf1cd5976726

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - rust
  run:
    - python

test:
  imports:
    - gap_statistic

about:
  home: http://github.com/
  license: Apache Software License